{% set name = "fps-terminals" %}
{% set version = "0.0.47" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_terminals-{{ version }}.tar.gz
  sha256: 79be329992d25de3ab634fdd0b05908c6a7c0a8adb39fa309c36dd207c86a477

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - fps >=0.0.8,<1
    - fps-auth-base <1
    - websockets >=10,<11
    - pywinpty >=2,<3  # [win]

test:
  imports:
    - fps_terminals

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  summary: An FPS plugin for the terminals API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
