{% set name = "fps-terminals" %}
{% set version = "0.0.44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_terminals-{{ version }}.tar.gz
  sha256: 2f2ac5c3ad01bbfec0c83635d2502294ded8132cb67a89a462d4f6d77d85957e

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - fps >=0.0.8,<1
    - fps-auth-base <1
    - websockets >=10,<11
    - pywinpty >=2,<3  # [win]

test:
  imports:
    - fps_terminals

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  summary: An FPS plugin for the terminals API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
