{% set name = "fps-terminals" %}
{% set version = "0.0.35" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_terminals-{{ version }}.tar.gz
  sha256: dbfb3736165bc6b406d88a767c2b5dac27bde5b9d082a99d836fe16490dc6a8b

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - fps <1
    - fps-auth <1
    - websockets >=10,<11
    - pywinpty >=2,<3  # [win]

test:
  imports:
    - fps_terminals

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  summary: An FPS plugin for the terminals API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
