{% set name = "fps-terminals" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_terminals-{{ version }}.tar.gz
  sha256: 61b8fb8807a43ced5906130922bf9de8035f2ad7d155bef8dccc8a54fb00036f

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - jupyverse-api >=0.1.4,<1
    - websockets
    - pywinpty  # [win]

test:
  imports:
    - fps_terminals

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  summary: An FPS plugin for the terminals API
  keywords: jupyter, server, fastapi, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
