{% set name = "fps-terminals" %}
{% set version = "0.0.32" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fps_terminals-{{ version }}.tar.gz
  sha256: 0f473072a4de48270cd89a59988df901f2348dfdeabe11cb42355e7c88de5107

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - fps >=0.0.8,<1.0.0
    - fps-auth >=0.0.30,<1.0.0
    - websockets <11.0.0

test:
  imports:
    - fps_terminals

about:
  home: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  summary: An FPS plugin for the terminals API
  keywords: jupyter, server, fastapi, pluggy, plugins
  dev_url: https://github.com/jupyter-server/jupyverse/tree/main/plugins/terminals
  license_file: COPYING.md
  license: BSD-3-Clause
  license_family: BSD

extra:
  recipe-maintainers:
    - davidbrochart
